/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  // tutorialSidebar: [
  docs: [
    // 'Introduction',
    'QucikStart',
    // 'Tutorials',
    {
      type: 'category',
      label: 'Tutorials',
      collapsible: true,
      collapsed: false,
      "link": {
        // "type": "generated-index",
        // "description": "Tutorials of SIMPO."
        type: 'doc',
        id: 'Tutorials/Tutorials', // Tutorials/Tutorials.mdx

      },
      items: [
        'Tutorials/Installtion',

        {
          type: 'category',
          label: 'BioModel',
          key: 'Tutorials/BioModel',
          collapsible: true,
          collapsed: true, // 默认折叠
          items: [
            'Tutorials/BioModel/Create',
            'Tutorials/BioModel/Edit',
          ],
        },

        // 'Tutorials/BioModel',
        {
          type: 'category',
          label: 'DataSet',
          key: 'Tutorials/DataSet',
          collapsible: true,
          collapsed: true,
          items: [
            'Tutorials/DataSet/Create',
            'Tutorials/DataSet/Edit',
          ],
        },
        'Tutorials/Project',
        // 'Tutorials/BioModel/Create',
        // 'Tutorials/BioModel/Edit',

        // {
        //   type: 'category',
        //   label: 'BioModel',
        //   collapsible: true,
        //   collapsed: true,
        //   "link": {
        //     type: "generated-index",
        //     description: "BioModel.",
        //     // type: 'doc',
        //     id: "BioModel1",
        //   },
        //   items: [
        //     'BioModel/Create',
        //     'BioModel/Edit',
        //   ]
        // },


      //   {
      //     type: 'category',
      //     label: 'Case Study',
      //     "link": {
      //       // "type": "generated-index",
      //       // "description": "Case Study of SIMPO."
      //       type: 'doc',
      //       id: 'Case Study',
      // },
      //     items: [
      //       'Case Study/ASM1',
      //     ]
      //   },



        // {
        //   type: 'category',
        //   label: 'SIMPO Pro',
        //   items: [
        //     'Changelog/SIMPO Pro/2023',
        //     'Changelog/SIMPO Pro/2022',
        //   ]
        // },
        // {
        //   type: 'category',
        //   label: 'SIMPO Dashboard',
        //   items: [
        //     'Changelog/SIMPO Dashboard/2023',
        //     'Changelog/SIMPO Dashboard/2022',
        //     'Changelog/SIMPO Dashboard/2021'
        //   ]
        // },


      ],
    },

    // SimpoCLI 是独立的产品使用文档，与 Tutorials 和 Case Study 同级。
    // 目录默认折叠；进入总览或任一命令页时，Docusaurus 会自动展开当前分支。
    {
      type: 'category',
      label: 'SimpoCLI',
      key: 'SimpoCLI',
      collapsible: true,
      collapsed: true,
      items: [
        // 总览作为分类内明确的第一页，确保折叠目录展开后能看到全部分页。
        'Tutorials/SimpoCLI',
        {
          type: 'category',
          label: 'Token',
          key: 'SimpoCLI/Token',
          collapsible: true,
          collapsed: true,
          items: [
            'Tutorials/SimpoCLI/configure',
            'Tutorials/SimpoCLI/me',
            'Tutorials/SimpoCLI/logout',
          ],
        },
        {
          type: 'category',
          label: 'BioModel',
          key: 'SimpoCLI/BioModel',
          collapsible: true,
          collapsed: true,
          items: [
            'Tutorials/SimpoCLI/create-biomodel',
            'Tutorials/SimpoCLI/get-biomodels',
            'Tutorials/SimpoCLI/get-biomodel',
            'Tutorials/SimpoCLI/update-biomodel',
            'Tutorials/SimpoCLI/sync-biomodel',
            'Tutorials/SimpoCLI/release-biomodel',
          ],
        },
        {
          type: 'category',
          label: 'DataSet',
          key: 'SimpoCLI/DataSet',
          collapsible: true,
          collapsed: true,
          items: [
            'Tutorials/SimpoCLI/create-dataset',
            'Tutorials/SimpoCLI/get-datasets',
            'Tutorials/SimpoCLI/get-dataset',
            'Tutorials/SimpoCLI/update-dataset',
            'Tutorials/SimpoCLI/sync-dataset',
            'Tutorials/SimpoCLI/release-dataset',
          ],
        },
        {
          type: 'category',
          label: 'Project',
          key: 'SimpoCLI/Project',
          collapsible: true,
          collapsed: true,
          items: [
            'Tutorials/SimpoCLI/create-project',
            'Tutorials/SimpoCLI/get-projects',
            'Tutorials/SimpoCLI/get-project',
            'Tutorials/SimpoCLI/update-project',
            'Tutorials/SimpoCLI/sync-project',
            'Tutorials/SimpoCLI/release-project',
            'Tutorials/SimpoCLI/project-variables',
            'Tutorials/SimpoCLI/set-project-variable',
          ],
        },
        {
          type: 'category',
          label: 'Calculation',
          key: 'SimpoCLI/Calculation',
          collapsible: true,
          collapsed: true,
          items: [
            'Tutorials/SimpoCLI/calculate',
            'Tutorials/SimpoCLI/get-calculation-status',
            'Tutorials/SimpoCLI/get-calculation-result',
            'Tutorials/SimpoCLI/stop-calculation',
          ],
        },
        // Skill 独立放在命令文档之后。按具体 Skill 功能分组，方便后续继续扩展。
        {
          type: 'category',
          label: 'Skill',
          key: 'SimpoCLI/Skill',
          collapsible: true,
          collapsed: true,
          items: [
            'Tutorials/SimpoCLI/simpo-skills',
            {
              type: 'category',
              label: 'SimpoCLI',
              key: 'SimpoCLI/Skill/SimpoCLI',
              collapsible: true,
              collapsed: true,
              items: [
                'Tutorials/SimpoCLI/simpo-cli-skill',
                {
                  type: 'category',
                  label: 'Codex',
                  key: 'SimpoCLI/Skill/SimpoCLI/Codex',
                  collapsible: true,
                  collapsed: true,
                  items: [
                    'Tutorials/SimpoCLI/simpo-cli-skill-codex-install',
                    'Tutorials/SimpoCLI/simpo-cli-skill-codex-usage',
                  ],
                },
                {
                  type: 'category',
                  label: 'Claude Code',
                  key: 'SimpoCLI/Skill/SimpoCLI/ClaudeCode',
                  collapsible: true,
                  collapsed: true,
                  items: [
                    'Tutorials/SimpoCLI/simpo-cli-skill-claude-code-install',
                    'Tutorials/SimpoCLI/simpo-cli-skill-claude-code-usage',
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'Create BioModel',
              key: 'SimpoCLI/Skill/CreateBioModel',
              collapsible: true,
              collapsed: true,
              items: [
                'Tutorials/SimpoCLI/biomodel-skill',
                {
                  type: 'category',
                  label: 'Codex',
                  key: 'SimpoCLI/Skill/CreateBioModel/Codex',
                  collapsible: true,
                  collapsed: true,
                  items: [
                    'Tutorials/SimpoCLI/biomodel-skill-codex-install',
                    'Tutorials/SimpoCLI/biomodel-skill-codex-usage',
                  ],
                },
                {
                  type: 'category',
                  label: 'Claude Code',
                  key: 'SimpoCLI/Skill/CreateBioModel/ClaudeCode',
                  collapsible: true,
                  collapsed: true,
                  items: [
                    'Tutorials/SimpoCLI/biomodel-skill-claude-code-install',
                    'Tutorials/SimpoCLI/biomodel-skill-claude-code-usage',
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'Create DataSet',
              key: 'SimpoCLI/Skill/CreateDataSet',
              collapsible: true,
              collapsed: true,
              items: [
                'Tutorials/SimpoCLI/dataset-skill',
                {
                  type: 'category',
                  label: 'Codex',
                  key: 'SimpoCLI/Skill/CreateDataSet/Codex',
                  collapsible: true,
                  collapsed: true,
                  items: [
                    'Tutorials/SimpoCLI/dataset-skill-codex-install',
                    'Tutorials/SimpoCLI/dataset-skill-codex-usage',
                  ],
                },
                {
                  type: 'category',
                  label: 'Claude Code',
                  key: 'SimpoCLI/Skill/CreateDataSet/ClaudeCode',
                  collapsible: true,
                  collapsed: true,
                  items: [
                    'Tutorials/SimpoCLI/dataset-skill-claude-code-install',
                    'Tutorials/SimpoCLI/dataset-skill-claude-code-usage',
                  ],
                },
              ],
            },
          ],
        },
      ],
    },

    {
      type: 'category',
      label: 'Case Study',
      collapsible: true,
      collapsed: true,
      "link": {
        "type": "generated-index",
        "description": "Case Study of SIMPO."
        // type: 'doc',
        // id: 'Case Study',
      },
      items: [
        // 'Case Study/ASM1',

        {
          type: 'category',
          label: 'AQUASIM',
          items: [
            'CaseStudy/AQUASIM/T2P17',
          ]
        },

        {
          type: 'category',
          label: 'Biological Wastewater Treatment: Examples and Exercises',
          items: [
            'CaseStudy/Biological Wastewater Treatment: Examples and Exercises/BWTEE 2.3.4',
          ]
        },




      ]
    },

    'Tips',



    // {
    //   type: 'category',
    //   label: 'Changelog',
    //   "link": {
    //     "type": "generated-index",
    //     "description": "Changelog of the core source code of SIMPO."
    //     // type: 'doc',
    //     // id: 'Changelog/index',
    //   },
    //   items: [

    //     {
    //       type: 'category',
    //       label: 'SIMPO Client',
    //       items: [
    //         'Changelog/SIMPO Client/2023',
    //       ]
    //     },

    //     {
    //       type: 'category',
    //       label: 'SIMPO Dash',
    //       items: [
    //         'Changelog/SIMPO Dash/2024',
    //         'Changelog/SIMPO Dash/2023',
    //         'Changelog/SIMPO Dash/2022',
    //         'Changelog/SIMPO Dash/2021'
    //       ]
    //     },

    //     {
    //       type: 'category',
    //       label: 'SIMPO',
    //       items: [
    //         'Changelog/SIMPO/2024',
    //         'Changelog/SIMPO/2023',
    //         'Changelog/SIMPO/2022',
    //         'Changelog/SIMPO/2021'
    //       ]
    //     },

    //     {
    //       type: 'category',
    //       label: 'SIMPO Pro',
    //       items: [
    //         'Changelog/SIMPO Pro/2024',
    //         'Changelog/SIMPO Pro/2023',
    //         'Changelog/SIMPO Pro/2022',
    //       ]
    //     },


    //     // {
    //     //   type: 'doc',
    //     //   id: 'Changelog/SIMPO/2023',
    //     // },
    //   ],
    // },

    // {
    //   type: 'category',
    //   label: 'Changelog',
    //   items: ['tutorial-basics/create-a-document'],
    // },
  ],

};

module.exports = sidebars;
